#!/bin/bash

# bash_profile

# Get the Git branch
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# Custom bash prompt
# Includes custom character for the prompt, path, and Git branch name.
# Source: kirsle.net/wizards/ps1.html
export PS1="\n\[$(tput bold)\]\[$(tput setaf 5)\]➜ \[$(tput setaf 6)\]\w\[$(tput setaf 3)\]\$(parse_git_branch) \[$(tput sgr0)\]"

## This is my Linux $PATH starting pt
export PATH="/usr/local/bin:$PATH"

## Added by Homebrew
export PATH="/usr/local/sbin:$PATH"

## rvm
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

## nvm: I'm not using this ATM
# export NVM_DIR="$HOME/.nvm"
# # . "$(brew --prefix nvm)/nvm.sh"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

## npm
## https://gist.github.com/DanHerbert/9520689
export PATH="$HOME/.npm-packages/bin:$PATH"

## yarn
## This seems to latch onto .npmrc settings, if you have it.
# export PATH="$PATH:`yarn global bin`"
export PATH="$HOME/.yarn/bin:$PATH"

## autojump
[[ -s $(brew --prefix)/etc/autojump.sh ]] && . $(brew --prefix)/etc/autojump.sh



#


# Symlinking: 
# ln -s ~/.dotfiles/bash/bash_profile ~/.bash_profile
# Verify the symlink:
# cd ~
# ls -la | grep .-\>

## from https://github.com/mdo/config/blob/master/.bash_profile
# export PATH=/opt/local/bin:/opt/local/sbin:${PATH}

# Aliases

## Shortcuts
alias ll='ls -al'
# alias editgit='atom ~/.gitconfig'
# alias editbash='atom ~/.bash_profile'
# alias resource='source ~/.bash_profile && echo "Done!"'
# alias vi=vim
# alias josh=sudo

## Git commands
alias log='git log'
alias diff='git diff'
alias branch='git branch'
alias st='git status'
alias fetch='git fetch'
alias push='git push origin head'
alias pull='git pull'
alias fp='fetch && pull'
alias gmm='git merge master'
alias gmghp='git merge gh-pages'
alias recent='git for-each-ref --sort=-committerdate refs/heads/'
alias branch_new="git for-each-ref --sort=-committerdate refs/heads/ --format='%(refname:short)'"

## Git commands added 170209
alias add='git add .'
alias pullr='git pull --rebase'
alias stash='git stash'

## Git branch switching
alias master='git co master'
alias ghp='git co gh-pages'

## SVN
# alias up='svn up'
# alias sst='svn st'

## Switch repos
DIR=~/work
alias h='cd ~/'
alias w='cd ${DIR}'

## Server guick starts
alias ss='script/server'
# alias js='jekyll serve --watch'
alias js='bundle exec jekyll serve'
alias ps='python -m SimpleHTTPServer 4000'
# alias gtest='testrb test/integration/bundle_test.rb'

## kill all mongo
## https://stackoverflow.com/questions/21431091/can-i-just-kill-mongod-to-stop-mongo
alias stopmongo='kill -2 `pgrep mongo`'
